### ISSUE TITLE
Creation of Game Objects

### ISSUE THREAD

**Issue by itgsod-Axel-IngelssonFredler** [itgsod-Axel-IngelssonFredler/Gymnasiearbete---Videogame#7]
We need to be able to create Game Objects via programming.

**Comment by itgsod-gustaf-wallin** [comment]
The creation of entities with varying ID's grant each and every object in the game, in it's current state, it's own identity.

**Comment by itgsod-fredrik-svahn** [comment]
We're now able to create entities/game objects via the Entity class. On creation, the entities are given a unique id which determines their position in the Entities array.
